name = "JuliaSteps"
uuid = "9fad2095-c3e9-400d-a146-28b3f996f85f"
authors = ["Hanjin Liu <liuhanjin-sc@g.ecc.u-tokyo.ac.jp>"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
