name = "JuliaSteps"
uuid = "9fad2095-c3e9-400d-a146-28b3f996f85f"
authors = ["Hanjin Liu <liuhanjin-sc@g.ecc.u-tokyo.ac.jp>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
DataStructures = "0.18"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
